FROM openjdk:%%BASE_TAG%%
LABEL mainteiner="%%MAINTAINER%%"

ENV CLOJURE_VERSION=%%BUILD_TOOL_VERSION%%

WORKDIR /tmp

%%ALPINE%% RUN apk add --update bash curl && rm -rf /var/cache/apk/*

RUN wget https://download.clojure.org/install/linux-install-$CLOJURE_VERSION.sh \
    && chmod +x linux-install-$CLOJURE_VERSION.sh \
    && ./linux-install-$CLOJURE_VERSION.sh

RUN clojure -e "(clojure-version)"