FROM openjdk:%%BASE_TAG%%
MAINTAINER %%MAINTAINER%%

ENV CLOJURE_VERSION=1.9.0.358

WORKDIR /tmp

%%ALPINE%% RUN apk add --update bash curl && rm -rf /var/cache/apk/*

RUN wget https://download.clojure.org/install/linux-install-$CLOJURE_VERSION.sh \
    && chmod +x linux-install-$CLOJURE_VERSION.sh \
    && ./linux-install-$CLOJURE_VERSION.sh

RUN clojure -e "(clojure-version)"