#!/usr/bin/env bash

set -eou pipefail

entrypoint=@@entrypoint@@

cmd=${1:''}

# check if the first arg starts with a hyphen
if [ "$#" -eq 0 ] || [ "${1#-}" != "$1" ]; then
  exec "${entrypoint}" "$@"
fi

if [[ -n "${cmd}" ]]; then
  # see if help for the subcommand is successful
  if "${entrypoint}" "${cmd}" --help >/dev/null 2>&1; then
    exec "${entrypoint}" "$@"
  fi
fi

exec "$@"
