#!/bin/bash

set -ex

if [[ $DOCKER_TAG == "boot"* ]]; then
  BUILD_TOOL=boot
else
  BUILD_TOOL=lein
fi

if [[ $DOCKER_TAG == "lein-"* || $DOCKER_TAG == "boot-"* ]]; then
  TOOL_VERSION=${DOCKER_TAG#*-}
  TOOL_VERSION=${TOOL_VERSION%-*}
fi

BUILD_CMD="docker build -t $IMAGE_NAME \
  --build-arg BUILD_TOOL=$BUILD_TOOL \
  $(if [[ -n $TOOL_VERSION ]]; then echo --build-arg TOOL_VERSION=$TOOL_VERSION; fi) \
  $BUILD_PATH"

$BUILD_CMD
