name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Install babashka
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        bb: 1.3.190
    - uses: actions/checkout@v4
    - name: Check for stale Dockerfiles
      run: |
        bb run dockerfiles
        git diff --exit-code
    - name: Run tests
      run: bb run test
