name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install babashka
      uses: DeLaGuardo/setup-clojure@10.1
      with:
        bb: 1.0.168
    - uses: actions/checkout@v3
    - name: Check for stale Dockerfiles
      run: |
        bb run dockerfiles
        git diff --exit-code
    - name: Run tests
      run: bb run test
