name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: turtlequeue/setup-babashka@v1.3.0
      with:
        babashka-version: 0.8.1
    - uses: actions/checkout@v2
    - name: Run tests
      run: bb run test
