name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install babashka
      uses: DeLaGuardo/setup-clojure@9.5
      with:
        bb: 0.10.163
    - uses: actions/checkout@v2
    - name: Run tests
      run: bb run test
