name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y clojure
    - uses: actions/checkout@v1
    - name: Run tests
      run: ./test.sh
